version: '3.8'
services:
 nginx:
  image: nginx:alpine
  ports: ["80:80"]
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  depends_on: [frontend, backend]

 backend:
  build: ./backend
  expose: ["5000"]

 frontend:
  build: ./frontend
  expose: ["80"]
